### ISSUE TITLE
Remove Even Numbers

### ISSUE THREAD

**Issue by omarqx** [mutlucodes/track-practice#2]
**Description:**

This problem involves array manipulation, specifically focusing on removing certain elements based on a condition. You are given an array of integers of size `n`, and your task is to remove all even numbers from this array. The challenge is to do this efficiently, both in terms of space and time complexity.

**Problem Statement:**

Develop an algorithm that, given an array of integers, removes all even integers from the array.

**Input:**

- An array of integers, `nums`.
- The size of the array, `n`.
- Example: `nums = [3, 4, 7, 12, 5, 8, 11]`

**Output:**

- The array `nums` after removing all even numbers.
- The size of the array after removal is not fixed.
- Example Output for the above input: `[3, 7, 5, 11]`

**Comment by mutlucodes** [comment]
Hi Omar! I added the solution for python and JS. Thank you!
